/**
 * CardIntel — Complete Indian Credit Card Issuer Registry
 *
 * Every known entity that issues, brands, or distributes credit cards in India.
 * Regulatory classification verified against RBI's list of regulated entities.
 *
 * NOTE: canIssueCreditCards is set based on known credit card programs.
 * Entities marked false may still have credit card programs not yet discovered.
 */

export interface IssuerSeed {
  name: string;
  shortName?: string;
  slug: string;
  issuerType:
    | "BANK"
    | "SMALL_FINANCE_BANK"
    | "FOREIGN_BANK"
    | "NBFC"
    | "PAYMENT_BANK"
    | "COOPERATIVE_BANK"
    | "FINTECH"
    | "MARKETPLACE"
    | "APP"
    | "PROGRAM_MANAGER"
    | "OTHER";
  canIssueCreditCards: boolean;
  canIssueBusinessCards: boolean;
  canIssueCoBrandedCards: boolean;
  canIssueSecuredCards: boolean;
  rbiRegulatedEntity: boolean;
  websiteUrl?: string;
  headquartersCity?: string;
  description?: string;
}

// ---------------------------------------------------------------------------
// Private Sector Banks
// ---------------------------------------------------------------------------

export const privateBanks: IssuerSeed[] = [
  {
    name: "HDFC Bank",
    shortName: "HDFC",
    slug: "hdfc-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.hdfcbank.com",
    headquartersCity: "Mumbai",
    description: "Largest private sector bank in India by assets. Major credit card issuer.",
  },
  {
    name: "ICICI Bank",
    shortName: "ICICI",
    slug: "icici-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.icicibank.com",
    headquartersCity: "Mumbai",
    description: "Second largest private sector bank. Major credit card issuer via ICICI Bank and Amazon co-brand.",
  },
  {
    name: "Axis Bank",
    slug: "axis-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.axisbank.com",
    headquartersCity: "Mumbai",
    description: "Third largest private sector bank. Strong credit card portfolio including Flipkart co-brand.",
  },
  {
    name: "Kotak Mahindra Bank",
    shortName: "Kotak",
    slug: "kotak-mahindra-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.kotak.com",
    headquartersCity: "Mumbai",
  },
  {
    name: "IDFC FIRST Bank",
    shortName: "IDFC FIRST",
    slug: "idfc-first-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.idfcfirstbank.com",
    headquartersCity: "Mumbai",
    description: "Known for competitive lifetime free credit card offerings.",
  },
  {
    name: "IndusInd Bank",
    shortName: "IndusInd",
    slug: "indusind-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.indusind.com",
    headquartersCity: "Mumbai",
  },
  {
    name: "RBL Bank",
    shortName: "RBL",
    slug: "rbl-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.rblbank.com",
    headquartersCity: "Mumbai",
    description: "Partners with multiple fintech brands for co-branded credit cards.",
  },
  {
    name: "YES Bank",
    shortName: "YES",
    slug: "yes-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.yesbank.in",
    headquartersCity: "Mumbai",
  },
  {
    name: "Federal Bank",
    slug: "federal-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.federalbank.co.in",
    headquartersCity: "Kochi",
    description: "Partners with OneCard/Fi for fintech credit cards.",
  },
  {
    name: "South Indian Bank",
    shortName: "SIB",
    slug: "south-indian-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.southindianbank.com",
    headquartersCity: "Thrissur",
  },
  {
    name: "Karnataka Bank",
    slug: "karnataka-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.karnatakabank.com",
    headquartersCity: "Mangalore",
  },
  {
    name: "CSB Bank",
    slug: "csb-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.csb.co.in",
    headquartersCity: "Thrissur",
  },
  {
    name: "DCB Bank",
    slug: "dcb-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.dcbbank.com",
    headquartersCity: "Mumbai",
  },
  {
    name: "City Union Bank",
    shortName: "CUB",
    slug: "city-union-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.cityunionbank.com",
    headquartersCity: "Kumbakonam",
  },
  {
    name: "Jammu & Kashmir Bank",
    shortName: "J&K Bank",
    slug: "jk-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.jkbank.com",
    headquartersCity: "Srinagar",
  },
  {
    name: "Tamilnad Mercantile Bank",
    shortName: "TMB",
    slug: "tamilnad-mercantile-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.tmb.in",
    headquartersCity: "Tuticorin",
  },
  {
    name: "Dhanlaxmi Bank",
    slug: "dhanlaxmi-bank",
    issuerType: "BANK",
    canIssueCreditCards: false, // Verify if currently issuing credit cards
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.dfrbank.com",
    headquartersCity: "Thrissur",
  },
  {
    name: "Karur Vysya Bank",
    shortName: "KVB",
    slug: "karur-vysya-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.kvb.co.in",
    headquartersCity: "Karur",
  },
  {
    name: "Bandhan Bank",
    slug: "bandhan-bank",
    issuerType: "BANK",
    canIssueCreditCards: false, // Verify — primarily microfinance/savings
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.bandhanbank.com",
    headquartersCity: "Kolkata",
  },
  {
    name: "IDBI Bank",
    slug: "idbi-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.idbibank.in",
    headquartersCity: "Mumbai",
    description: "Government-owned bank (LIC majority stake). Issues credit cards.",
  },
];

// ---------------------------------------------------------------------------
// PSU / Government / Public Sector Banks
// ---------------------------------------------------------------------------

export const psuBanks: IssuerSeed[] = [
  {
    name: "State Bank of India",
    shortName: "SBI",
    slug: "sbi",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.sbi.co.in",
    headquartersCity: "Mumbai",
    description: "Largest bank in India. Credit cards issued via SBI Card (SBI Cards & Payment Services Ltd).",
  },
  {
    name: "SBI Card",
    slug: "sbi-card",
    issuerType: "NBFC",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.sbicard.com",
    headquartersCity: "Gurugram",
    description: "SBI Cards & Payment Services Ltd. Subsidiary of SBI. India's largest credit card issuer by cards outstanding.",
  },
  {
    name: "Punjab National Bank",
    shortName: "PNB",
    slug: "pnb",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.pnbindia.in",
    headquartersCity: "New Delhi",
  },
  {
    name: "Bank of Baroda",
    shortName: "BoB",
    slug: "bank-of-baroda",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.bankofbaroda.in",
    headquartersCity: "Vadodara",
    description: "Credit cards issued via BOBCARD (BOB Financial Solutions Ltd).",
  },
  {
    name: "BOB Financial Solutions (BOBCARD)",
    shortName: "BOBCARD",
    slug: "bobcard",
    issuerType: "NBFC",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.bobfinancial.com",
    headquartersCity: "Mumbai",
    description: "Wholly-owned subsidiary of Bank of Baroda. Issues all BoB credit cards.",
  },
  {
    name: "Canara Bank",
    slug: "canara-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.canarabank.com",
    headquartersCity: "Bangalore",
  },
  {
    name: "Union Bank of India",
    shortName: "Union Bank",
    slug: "union-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.unionbankofindia.co.in",
    headquartersCity: "Mumbai",
  },
  {
    name: "Bank of India",
    shortName: "BoI",
    slug: "bank-of-india",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.bankofindia.co.in",
    headquartersCity: "Mumbai",
  },
  {
    name: "Indian Bank",
    slug: "indian-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.indianbank.in",
    headquartersCity: "Chennai",
  },
  {
    name: "Central Bank of India",
    slug: "central-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.centralbankofindia.co.in",
    headquartersCity: "Mumbai",
  },
  {
    name: "UCO Bank",
    slug: "uco-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.ucobank.com",
    headquartersCity: "Kolkata",
  },
  {
    name: "Indian Overseas Bank",
    shortName: "IOB",
    slug: "iob",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.iob.in",
    headquartersCity: "Chennai",
  },
  {
    name: "Bank of Maharashtra",
    shortName: "BoM",
    slug: "bank-of-maharashtra",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.bankofmaharashtra.in",
    headquartersCity: "Pune",
  },
  {
    name: "Punjab & Sind Bank",
    shortName: "P&S Bank",
    slug: "punjab-sind-bank",
    issuerType: "BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.psbindia.com",
    headquartersCity: "New Delhi",
  },
];

// ---------------------------------------------------------------------------
// Small Finance Banks
// ---------------------------------------------------------------------------

export const smallFinanceBanks: IssuerSeed[] = [
  {
    name: "AU Small Finance Bank",
    shortName: "AU SFB",
    slug: "au-small-finance-bank",
    issuerType: "SMALL_FINANCE_BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: true,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.aubank.in",
    headquartersCity: "Jaipur",
    description: "First Small Finance Bank to issue credit cards in India.",
  },
  {
    name: "ESAF Small Finance Bank",
    shortName: "ESAF SFB",
    slug: "esaf-sfb",
    issuerType: "SMALL_FINANCE_BANK",
    canIssueCreditCards: false, // Verify current status
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.esafbank.com",
    headquartersCity: "Thrissur",
  },
  {
    name: "Equitas Small Finance Bank",
    shortName: "Equitas SFB",
    slug: "equitas-sfb",
    issuerType: "SMALL_FINANCE_BANK",
    canIssueCreditCards: false, // Verify current status
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.equitasbank.com",
    headquartersCity: "Chennai",
  },
  {
    name: "Ujjivan Small Finance Bank",
    shortName: "Ujjivan SFB",
    slug: "ujjivan-sfb",
    issuerType: "SMALL_FINANCE_BANK",
    canIssueCreditCards: false, // Verify current status
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.ujjivansfb.in",
    headquartersCity: "Bangalore",
  },
  {
    name: "Jana Small Finance Bank",
    shortName: "Jana SFB",
    slug: "jana-sfb",
    issuerType: "SMALL_FINANCE_BANK",
    canIssueCreditCards: false, // Verify current status
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.janabank.com",
    headquartersCity: "Bangalore",
  },
  {
    name: "Unity Small Finance Bank",
    shortName: "Unity SFB",
    slug: "unity-sfb",
    issuerType: "SMALL_FINANCE_BANK",
    canIssueCreditCards: false, // Verify current status
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.unitysfb.in",
    headquartersCity: "Mumbai",
  },
  {
    name: "Slice (NKS Small Finance Bank)",
    shortName: "Slice SFB",
    slug: "slice-sfb",
    issuerType: "SMALL_FINANCE_BANK",
    canIssueCreditCards: true, // Now a bank, issues its own cards
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.sliceit.com",
    headquartersCity: "Bangalore",
    description: "Formerly fintech Slice, became Small Finance Bank after merger with North East Small Finance Bank.",
  },
];

// ---------------------------------------------------------------------------
// Foreign Banks
// ---------------------------------------------------------------------------

export const foreignBanks: IssuerSeed[] = [
  {
    name: "American Express",
    shortName: "Amex",
    slug: "amex",
    issuerType: "FOREIGN_BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.americanexpress.com/in/",
    headquartersCity: "Gurugram",
    description: "Both card network and direct issuer. Issues premium charge and credit cards.",
  },
  {
    name: "HSBC",
    slug: "hsbc",
    issuerType: "FOREIGN_BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.hsbc.co.in",
    headquartersCity: "Mumbai",
  },
  {
    name: "Standard Chartered Bank",
    shortName: "StanChart",
    slug: "standard-chartered",
    issuerType: "FOREIGN_BANK",
    canIssueCreditCards: true,
    canIssueBusinessCards: true,
    canIssueCoBrandedCards: true,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.sc.com/in/",
    headquartersCity: "Mumbai",
  },
  {
    name: "Citibank",
    slug: "citibank",
    issuerType: "FOREIGN_BANK",
    canIssueCreditCards: false, // Consumer banking exited India; cards migrated to Axis
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.citibank.co.in",
    headquartersCity: "Mumbai",
    description: "Exited consumer banking in India. Credit card portfolio acquired by Axis Bank.",
  },
  {
    name: "Deutsche Bank",
    slug: "deutsche-bank",
    issuerType: "FOREIGN_BANK",
    canIssueCreditCards: false, // Verify current India credit card status
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: true,
    websiteUrl: "https://www.db.com/india",
    headquartersCity: "Mumbai",
  },
];

// ---------------------------------------------------------------------------
// Fintech / App-Led Brands (these are NOT issuers — they partner with banks)
// ---------------------------------------------------------------------------

export const fintechBrands: IssuerSeed[] = [
  {
    name: "OneCard",
    slug: "onecard",
    issuerType: "FINTECH",
    canIssueCreditCards: false, // Issues via partner banks (Federal, IDFC FIRST, etc.)
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.getonecard.app",
    headquartersCity: "Pune",
    description: "Fintech credit card platform. Cards issued by partner banks (Federal Bank, Bob Card, etc.).",
  },
  {
    name: "Jupiter",
    slug: "jupiter",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.jupiter.money",
    headquartersCity: "Mumbai",
    description: "Neobanking platform. Credit card issued via partner bank.",
  },
  {
    name: "Uni",
    slug: "uni",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.uni.club",
    headquartersCity: "Bangalore",
    description: "Pay 1/3rd card. Verify if current product qualifies as credit card.",
  },
  {
    name: "Scapia",
    slug: "scapia",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.scapia.com",
    headquartersCity: "Bangalore",
    description: "Travel-focused credit card. Card issued by partner bank.",
  },
  {
    name: "Kiwi",
    slug: "kiwi",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.kiwi.com",
    headquartersCity: "Bangalore",
    description: "Credit card on UPI. Verify current product and issuing partner.",
  },
  {
    name: "Fi",
    slug: "fi",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://fi.money",
    headquartersCity: "Bangalore",
    description: "Neobanking platform by epiFi. Credit card via partner bank.",
  },
  {
    name: "super.money",
    slug: "super-money",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.super.money",
    headquartersCity: "Mumbai",
    description: "Verify if current product qualifies as credit card.",
  },
  {
    name: "Fibe",
    slug: "fibe",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.fibe.in",
    headquartersCity: "Bangalore",
    description: "Formerly EarlySalary. Verify if credit card product is active.",
  },
  {
    name: "Zolve",
    slug: "zolve",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.zolve.com",
    headquartersCity: "Bangalore",
    description: "Cross-border neobank. Verify India credit card status.",
  },
];

// ---------------------------------------------------------------------------
// Marketplaces (these aggregate cards but do NOT issue them)
// ---------------------------------------------------------------------------

export const marketplaces: IssuerSeed[] = [
  {
    name: "Paisabazaar",
    slug: "paisabazaar",
    issuerType: "MARKETPLACE",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.paisabazaar.com",
    headquartersCity: "Gurugram",
    description: "Financial marketplace. Does not issue credit cards. May offer co-branded cards via partner banks.",
  },
  {
    name: "BankBazaar",
    slug: "bankbazaar",
    issuerType: "MARKETPLACE",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.bankbazaar.com",
    headquartersCity: "Chennai",
    description: "Financial marketplace. Does not issue credit cards.",
  },
  {
    name: "CRED",
    slug: "cred",
    issuerType: "FINTECH",
    canIssueCreditCards: false,
    canIssueBusinessCards: false,
    canIssueCoBrandedCards: false,
    canIssueSecuredCards: false,
    rbiRegulatedEntity: false,
    websiteUrl: "https://www.cred.club",
    headquartersCity: "Bangalore",
    description: "Credit card bill payment platform. Verify if any CRED-branded credit card product exists.",
  },
];

// ---------------------------------------------------------------------------
// All issuers combined
// ---------------------------------------------------------------------------

export const allIssuers: IssuerSeed[] = [
  ...privateBanks,
  ...psuBanks,
  ...smallFinanceBanks,
  ...foreignBanks,
  ...fintechBrands,
  ...marketplaces,
];
